spring:
  application:
    name: springboot-temp
  profiles:
    active: database,config
    include:
      - redis
      - database
      - excleTem
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: true